name: Test Exit

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Exit 1 does not stop step
        run: |
          echo "This will run: before exit"
          exit 1
          echo "This will still run: after exit"
